### ISSUE TITLE
not able to install helm plugin after 0.7.0 release

### ISSUE THREAD

**Issue by coffeepac** [app-registry/appr#80]
now that https://github.com/app-registry/appr-helm-plugin has a windows release the name of the file that gets downloaded needs to be either passed in from the command line or be set based on what the operating system is.

the current solution doesn't work and fails with the following output:

> appr plugins install helm
Traceback (most recent call last):
  File "/usr/bin/appr", line 6, in <module>
    cli()
  File "/usr/lib/python2.7/site-packages/appr/commands/cli.py", line 56, in cli
    args.func(args)
  File "/usr/lib/python2.7/site-packages/appr/commands/plugins.py", line 70, in _install
    cmd.status = cls.plugins[plugin_name]['install_method'](plugin, cls.plugins[plugin_name])
  File "/usr/lib/python2.7/site-packages/appr/commands/plugins.py", line 21, in install_helm_plugin
    res.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://github.com/app-registry/appr-helm-plugin/releases/download/v0.7.0/registry-helm-plugin.tar.gz

**Comment by ant31** [comment]
should be fixed by #82
