### ISSUE TITLE
BUG: appr barfs with error when chart.yaml is not found [UnboundLocalError: local variable 'mfile' referenced before assignment]

### ISSUE THREAD

**Issue by notjames** [app-registry/appr#85]
```
Traceback (most recent call last):
  File "bin/appr", line 6, in <module>
    
  File "appr/commands/cli.py", line 74, in cli
  File "appr/commands/command_base.py", line 130, in call
  File "appr/commands/command_base.py", line 134, in exec_cmd
  File "appr/commands/push.py", line 139, in _call
  File "appr/commands/push.py", line 134, in _init
  File "appr/commands/push.py", line 94, in _chart
  File "appr/formats/helm/manifest_chart.py", line 20, in __init__
  File "appr/formats/helm/manifest_chart.py", line 39, in _load_from_path
UnboundLocalError: local variable 'mfile' referenced before assignment
[24674] Failed to execute script appr
```

**Comment by notjames** [comment]
PR submitted #86
